### ISSUE TITLE
Invalid field name in Opt_Output_Http::sendHeaders()

### ISSUE THREAD

**Issue by cookie-at-zeno-pl** [OPL/Open-Power-Template#1]
I don't know if I'm wrong but I think there is a bug in this method - a misspelled variable name. Found in OPT 2.0.6.

Opt_Output_Http::sendHeaders() line 94:

``` php
foreach($this->headers as $name => $value)
```

To display the buffered headers, we use `$this->headers`, but everywhere else we see `$this->_headers`. So, I think the problem is quite serious - the buffered headers are not sent.

Regards,

**Comment by zyxist** [comment]
Fixed in `123be39`
